//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/ari/Desktop/C# Projects/ARISL/antlrfiles/Arisl.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ArislParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IArislListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] ArislParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] ArislParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>functionDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDeclID([NotNull] ArislParser.FunctionDeclIDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>functionDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDeclID([NotNull] ArislParser.FunctionDeclIDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>delegateDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDelegateDeclID([NotNull] ArislParser.DelegateDeclIDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>delegateDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDelegateDeclID([NotNull] ArislParser.DelegateDeclIDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>constructorDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructorDeclID([NotNull] ArislParser.ConstructorDeclIDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>constructorDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructorDeclID([NotNull] ArislParser.ConstructorDeclIDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>classDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDeclID([NotNull] ArislParser.ClassDeclIDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>classDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDeclID([NotNull] ArislParser.ClassDeclIDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>structDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDeclID([NotNull] ArislParser.StructDeclIDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>structDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDeclID([NotNull] ArislParser.StructDeclIDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>recordDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecordDeclID([NotNull] ArislParser.RecordDeclIDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>recordDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecordDeclID([NotNull] ArislParser.RecordDeclIDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>enumDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDeclID([NotNull] ArislParser.EnumDeclIDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>enumDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDeclID([NotNull] ArislParser.EnumDeclIDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>interfaceDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceDeclID([NotNull] ArislParser.InterfaceDeclIDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>interfaceDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceDeclID([NotNull] ArislParser.InterfaceDeclIDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ifStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatementID([NotNull] ArislParser.IfStatementIDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ifStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatementID([NotNull] ArislParser.IfStatementIDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>whileStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatementID([NotNull] ArislParser.WhileStatementIDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>whileStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatementID([NotNull] ArislParser.WhileStatementIDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>forStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatementID([NotNull] ArislParser.ForStatementIDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>forStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatementID([NotNull] ArislParser.ForStatementIDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>forEachStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForEachStatementID([NotNull] ArislParser.ForEachStatementIDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>forEachStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForEachStatementID([NotNull] ArislParser.ForEachStatementIDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>returnStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatementID([NotNull] ArislParser.ReturnStatementIDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>returnStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatementID([NotNull] ArislParser.ReturnStatementIDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>objectCreationStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectCreationStatementID([NotNull] ArislParser.ObjectCreationStatementIDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>objectCreationStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectCreationStatementID([NotNull] ArislParser.ObjectCreationStatementIDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>tryCatchStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTryCatchStatementID([NotNull] ArislParser.TryCatchStatementIDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>tryCatchStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTryCatchStatementID([NotNull] ArislParser.TryCatchStatementIDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>repeatUntilStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeatUntilStatementID([NotNull] ArislParser.RepeatUntilStatementIDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>repeatUntilStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeatUntilStatementID([NotNull] ArislParser.RepeatUntilStatementIDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>switchStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchStatementID([NotNull] ArislParser.SwitchStatementIDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>switchStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchStatementID([NotNull] ArislParser.SwitchStatementIDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expressionStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionStatementID([NotNull] ArislParser.ExpressionStatementIDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expressionStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionStatementID([NotNull] ArislParser.ExpressionStatementIDContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.delegateDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDelegateDecl([NotNull] ArislParser.DelegateDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.delegateDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDelegateDecl([NotNull] ArislParser.DelegateDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.recordDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecordDecl([NotNull] ArislParser.RecordDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.recordDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecordDecl([NotNull] ArislParser.RecordDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDecl([NotNull] ArislParser.FunctionDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDecl([NotNull] ArislParser.FunctionDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.repeatUntilStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeatUntilStatement([NotNull] ArislParser.RepeatUntilStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.repeatUntilStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeatUntilStatement([NotNull] ArislParser.RepeatUntilStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.classDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDecl([NotNull] ArislParser.ClassDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.classDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDecl([NotNull] ArislParser.ClassDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.constructorDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructorDecl([NotNull] ArislParser.ConstructorDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.constructorDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructorDecl([NotNull] ArislParser.ConstructorDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.structDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDecl([NotNull] ArislParser.StructDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.structDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDecl([NotNull] ArislParser.StructDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.enumDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDecl([NotNull] ArislParser.EnumDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.enumDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDecl([NotNull] ArislParser.EnumDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.interfaceDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceDecl([NotNull] ArislParser.InterfaceDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.interfaceDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceDecl([NotNull] ArislParser.InterfaceDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] ArislParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] ArislParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] ArislParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] ArislParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] ArislParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] ArislParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.forEachStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForEachStatement([NotNull] ArislParser.ForEachStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.forEachStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForEachStatement([NotNull] ArislParser.ForEachStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] ArislParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] ArislParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.operatorOverloadStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorOverloadStatement([NotNull] ArislParser.OperatorOverloadStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.operatorOverloadStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorOverloadStatement([NotNull] ArislParser.OperatorOverloadStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.objectCreation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectCreation([NotNull] ArislParser.ObjectCreationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.objectCreation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectCreation([NotNull] ArislParser.ObjectCreationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.interfaceBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceBlock([NotNull] ArislParser.InterfaceBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.interfaceBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceBlock([NotNull] ArislParser.InterfaceBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.interfaceMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceMember([NotNull] ArislParser.InterfaceMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.interfaceMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceMember([NotNull] ArislParser.InterfaceMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.functionSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionSignature([NotNull] ArislParser.FunctionSignatureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.functionSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionSignature([NotNull] ArislParser.FunctionSignatureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] ArislParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] ArislParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] ArislParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] ArislParser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionStatement([NotNull] ArislParser.ExpressionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionStatement([NotNull] ArislParser.ExpressionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PrimaryExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpression([NotNull] ArislParser.PrimaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PrimaryExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpression([NotNull] ArislParser.PrimaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryExpression([NotNull] ArislParser.BinaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryExpression([NotNull] ArislParser.BinaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenthesisExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesisExpression([NotNull] ArislParser.ParenthesisExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenthesisExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesisExpression([NotNull] ArislParser.ParenthesisExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PrefixExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixExpression([NotNull] ArislParser.PrefixExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PrefixExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixExpression([NotNull] ArislParser.PrefixExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] ArislParser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] ArislParser.UnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>literalPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralPrimary([NotNull] ArislParser.LiteralPrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>literalPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralPrimary([NotNull] ArislParser.LiteralPrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>tuplePrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTuplePrimary([NotNull] ArislParser.TuplePrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>tuplePrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTuplePrimary([NotNull] ArislParser.TuplePrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>identifierPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierPrimary([NotNull] ArislParser.IdentifierPrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>identifierPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierPrimary([NotNull] ArislParser.IdentifierPrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>methodCallPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodCallPrimary([NotNull] ArislParser.MethodCallPrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>methodCallPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodCallPrimary([NotNull] ArislParser.MethodCallPrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>tableCallPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableCallPrimary([NotNull] ArislParser.TableCallPrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>tableCallPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableCallPrimary([NotNull] ArislParser.TableCallPrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>blockPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockPrimary([NotNull] ArislParser.BlockPrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>blockPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockPrimary([NotNull] ArislParser.BlockPrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>listPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListPrimary([NotNull] ArislParser.ListPrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>listPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListPrimary([NotNull] ArislParser.ListPrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>genericTypePrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericTypePrimary([NotNull] ArislParser.GenericTypePrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>genericTypePrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericTypePrimary([NotNull] ArislParser.GenericTypePrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>typePrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypePrimary([NotNull] ArislParser.TypePrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>typePrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypePrimary([NotNull] ArislParser.TypePrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTuple([NotNull] ArislParser.TupleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTuple([NotNull] ArislParser.TupleContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>varArgs</c>
	/// labeled alternative in <see cref="ArislParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarArgs([NotNull] ArislParser.VarArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>varArgs</c>
	/// labeled alternative in <see cref="ArislParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarArgs([NotNull] ArislParser.VarArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>args</c>
	/// labeled alternative in <see cref="ArislParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgs([NotNull] ArislParser.ArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>args</c>
	/// labeled alternative in <see cref="ArislParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgs([NotNull] ArislParser.ArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] ArislParser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] ArislParser.ParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.prefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefix([NotNull] ArislParser.PrefixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.prefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefix([NotNull] ArislParser.PrefixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.unaryOP"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryOP([NotNull] ArislParser.UnaryOPContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.unaryOP"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryOP([NotNull] ArislParser.UnaryOPContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodCall([NotNull] ArislParser.MethodCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodCall([NotNull] ArislParser.MethodCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.tableCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableCall([NotNull] ArislParser.TableCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.tableCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableCall([NotNull] ArislParser.TableCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] ArislParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] ArislParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.binaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryOp([NotNull] ArislParser.BinaryOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.binaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryOp([NotNull] ArislParser.BinaryOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.tryCatchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTryCatchStatement([NotNull] ArislParser.TryCatchStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.tryCatchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTryCatchStatement([NotNull] ArislParser.TryCatchStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchStatement([NotNull] ArislParser.SwitchStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchStatement([NotNull] ArislParser.SwitchStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.caseBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseBlock([NotNull] ArislParser.CaseBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.caseBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseBlock([NotNull] ArislParser.CaseBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.defaultBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultBlock([NotNull] ArislParser.DefaultBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.defaultBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultBlock([NotNull] ArislParser.DefaultBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModifier([NotNull] ArislParser.ModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModifier([NotNull] ArislParser.ModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVisibility([NotNull] ArislParser.VisibilityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVisibility([NotNull] ArislParser.VisibilityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] ArislParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] ArislParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.varType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarType([NotNull] ArislParser.VarTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.varType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarType([NotNull] ArislParser.VarTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.simpleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleType([NotNull] ArislParser.SimpleTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.simpleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleType([NotNull] ArislParser.SimpleTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.tupleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTupleType([NotNull] ArislParser.TupleTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.tupleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTupleType([NotNull] ArislParser.TupleTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.genericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericType([NotNull] ArislParser.GenericTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.genericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericType([NotNull] ArislParser.GenericTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.nestedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNestedType([NotNull] ArislParser.NestedTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.nestedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNestedType([NotNull] ArislParser.NestedTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.castType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCastType([NotNull] ArislParser.CastTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.castType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCastType([NotNull] ArislParser.CastTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.end"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnd([NotNull] ArislParser.EndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.end"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnd([NotNull] ArislParser.EndContext context);
}
