//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/ari/Desktop/C# Projects/ARISL/antlrfiles/Arisl.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IArislListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ArislBaseListener : IArislListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] ArislParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] ArislParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>functionDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDeclID([NotNull] ArislParser.FunctionDeclIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>functionDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDeclID([NotNull] ArislParser.FunctionDeclIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>delegateDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDelegateDeclID([NotNull] ArislParser.DelegateDeclIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>delegateDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDelegateDeclID([NotNull] ArislParser.DelegateDeclIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>constructorDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructorDeclID([NotNull] ArislParser.ConstructorDeclIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>constructorDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructorDeclID([NotNull] ArislParser.ConstructorDeclIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>classDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDeclID([NotNull] ArislParser.ClassDeclIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>classDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDeclID([NotNull] ArislParser.ClassDeclIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>structDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDeclID([NotNull] ArislParser.StructDeclIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>structDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDeclID([NotNull] ArislParser.StructDeclIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>recordDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecordDeclID([NotNull] ArislParser.RecordDeclIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>recordDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecordDeclID([NotNull] ArislParser.RecordDeclIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>enumDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDeclID([NotNull] ArislParser.EnumDeclIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>enumDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDeclID([NotNull] ArislParser.EnumDeclIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>interfaceDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceDeclID([NotNull] ArislParser.InterfaceDeclIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>interfaceDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceDeclID([NotNull] ArislParser.InterfaceDeclIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ifStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatementID([NotNull] ArislParser.IfStatementIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ifStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatementID([NotNull] ArislParser.IfStatementIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>whileStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatementID([NotNull] ArislParser.WhileStatementIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>whileStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatementID([NotNull] ArislParser.WhileStatementIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>forStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatementID([NotNull] ArislParser.ForStatementIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>forStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatementID([NotNull] ArislParser.ForStatementIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>forEachStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForEachStatementID([NotNull] ArislParser.ForEachStatementIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>forEachStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForEachStatementID([NotNull] ArislParser.ForEachStatementIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>returnStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatementID([NotNull] ArislParser.ReturnStatementIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>returnStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatementID([NotNull] ArislParser.ReturnStatementIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>objectCreationStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectCreationStatementID([NotNull] ArislParser.ObjectCreationStatementIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>objectCreationStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectCreationStatementID([NotNull] ArislParser.ObjectCreationStatementIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>tryCatchStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTryCatchStatementID([NotNull] ArislParser.TryCatchStatementIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>tryCatchStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTryCatchStatementID([NotNull] ArislParser.TryCatchStatementIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>repeatUntilStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeatUntilStatementID([NotNull] ArislParser.RepeatUntilStatementIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>repeatUntilStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeatUntilStatementID([NotNull] ArislParser.RepeatUntilStatementIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>switchStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchStatementID([NotNull] ArislParser.SwitchStatementIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>switchStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchStatementID([NotNull] ArislParser.SwitchStatementIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expressionStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionStatementID([NotNull] ArislParser.ExpressionStatementIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expressionStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionStatementID([NotNull] ArislParser.ExpressionStatementIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.delegateDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDelegateDecl([NotNull] ArislParser.DelegateDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.delegateDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDelegateDecl([NotNull] ArislParser.DelegateDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.recordDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecordDecl([NotNull] ArislParser.RecordDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.recordDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecordDecl([NotNull] ArislParser.RecordDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.functionDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDecl([NotNull] ArislParser.FunctionDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.functionDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDecl([NotNull] ArislParser.FunctionDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.repeatUntilStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeatUntilStatement([NotNull] ArislParser.RepeatUntilStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.repeatUntilStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeatUntilStatement([NotNull] ArislParser.RepeatUntilStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.classDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDecl([NotNull] ArislParser.ClassDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.classDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDecl([NotNull] ArislParser.ClassDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.constructorDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructorDecl([NotNull] ArislParser.ConstructorDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.constructorDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructorDecl([NotNull] ArislParser.ConstructorDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.structDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDecl([NotNull] ArislParser.StructDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.structDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDecl([NotNull] ArislParser.StructDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.enumDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDecl([NotNull] ArislParser.EnumDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.enumDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDecl([NotNull] ArislParser.EnumDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.interfaceDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceDecl([NotNull] ArislParser.InterfaceDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.interfaceDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceDecl([NotNull] ArislParser.InterfaceDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] ArislParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] ArislParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] ArislParser.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] ArislParser.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] ArislParser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] ArislParser.ForStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.forEachStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForEachStatement([NotNull] ArislParser.ForEachStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.forEachStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForEachStatement([NotNull] ArislParser.ForEachStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] ArislParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] ArislParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.operatorOverloadStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorOverloadStatement([NotNull] ArislParser.OperatorOverloadStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.operatorOverloadStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorOverloadStatement([NotNull] ArislParser.OperatorOverloadStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.objectCreation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectCreation([NotNull] ArislParser.ObjectCreationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.objectCreation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectCreation([NotNull] ArislParser.ObjectCreationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.interfaceBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceBlock([NotNull] ArislParser.InterfaceBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.interfaceBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceBlock([NotNull] ArislParser.InterfaceBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.interfaceMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceMember([NotNull] ArislParser.InterfaceMemberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.interfaceMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceMember([NotNull] ArislParser.InterfaceMemberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.functionSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionSignature([NotNull] ArislParser.FunctionSignatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.functionSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionSignature([NotNull] ArislParser.FunctionSignatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] ArislParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] ArislParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList([NotNull] ArislParser.ListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList([NotNull] ArislParser.ListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionStatement([NotNull] ArislParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionStatement([NotNull] ArislParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PrimaryExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExpression([NotNull] ArislParser.PrimaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PrimaryExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExpression([NotNull] ArislParser.PrimaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryExpression([NotNull] ArislParser.BinaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryExpression([NotNull] ArislParser.BinaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenthesisExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenthesisExpression([NotNull] ArislParser.ParenthesisExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenthesisExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenthesisExpression([NotNull] ArislParser.ParenthesisExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PrefixExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefixExpression([NotNull] ArislParser.PrefixExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PrefixExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefixExpression([NotNull] ArislParser.PrefixExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExpression([NotNull] ArislParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExpression([NotNull] ArislParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>literalPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralPrimary([NotNull] ArislParser.LiteralPrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>literalPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralPrimary([NotNull] ArislParser.LiteralPrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>tuplePrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTuplePrimary([NotNull] ArislParser.TuplePrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>tuplePrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTuplePrimary([NotNull] ArislParser.TuplePrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>identifierPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierPrimary([NotNull] ArislParser.IdentifierPrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>identifierPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierPrimary([NotNull] ArislParser.IdentifierPrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>methodCallPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodCallPrimary([NotNull] ArislParser.MethodCallPrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>methodCallPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodCallPrimary([NotNull] ArislParser.MethodCallPrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>tableCallPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableCallPrimary([NotNull] ArislParser.TableCallPrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>tableCallPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableCallPrimary([NotNull] ArislParser.TableCallPrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>blockPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockPrimary([NotNull] ArislParser.BlockPrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>blockPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockPrimary([NotNull] ArislParser.BlockPrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>listPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListPrimary([NotNull] ArislParser.ListPrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>listPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListPrimary([NotNull] ArislParser.ListPrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>genericTypePrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericTypePrimary([NotNull] ArislParser.GenericTypePrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>genericTypePrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericTypePrimary([NotNull] ArislParser.GenericTypePrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>typePrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypePrimary([NotNull] ArislParser.TypePrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>typePrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypePrimary([NotNull] ArislParser.TypePrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.tuple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTuple([NotNull] ArislParser.TupleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.tuple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTuple([NotNull] ArislParser.TupleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>varArgs</c>
	/// labeled alternative in <see cref="ArislParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarArgs([NotNull] ArislParser.VarArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>varArgs</c>
	/// labeled alternative in <see cref="ArislParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarArgs([NotNull] ArislParser.VarArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>args</c>
	/// labeled alternative in <see cref="ArislParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgs([NotNull] ArislParser.ArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>args</c>
	/// labeled alternative in <see cref="ArislParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgs([NotNull] ArislParser.ArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam([NotNull] ArislParser.ParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam([NotNull] ArislParser.ParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.prefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefix([NotNull] ArislParser.PrefixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.prefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefix([NotNull] ArislParser.PrefixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.unaryOP"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryOP([NotNull] ArislParser.UnaryOPContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.unaryOP"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryOP([NotNull] ArislParser.UnaryOPContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.methodCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodCall([NotNull] ArislParser.MethodCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.methodCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodCall([NotNull] ArislParser.MethodCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.tableCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableCall([NotNull] ArislParser.TableCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.tableCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableCall([NotNull] ArislParser.TableCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] ArislParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] ArislParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.binaryOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryOp([NotNull] ArislParser.BinaryOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.binaryOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryOp([NotNull] ArislParser.BinaryOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.tryCatchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTryCatchStatement([NotNull] ArislParser.TryCatchStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.tryCatchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTryCatchStatement([NotNull] ArislParser.TryCatchStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.switchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchStatement([NotNull] ArislParser.SwitchStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.switchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchStatement([NotNull] ArislParser.SwitchStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.caseBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseBlock([NotNull] ArislParser.CaseBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.caseBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseBlock([NotNull] ArislParser.CaseBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.defaultBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultBlock([NotNull] ArislParser.DefaultBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.defaultBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultBlock([NotNull] ArislParser.DefaultBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModifier([NotNull] ArislParser.ModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModifier([NotNull] ArislParser.ModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.visibility"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVisibility([NotNull] ArislParser.VisibilityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.visibility"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVisibility([NotNull] ArislParser.VisibilityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] ArislParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] ArislParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.varType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarType([NotNull] ArislParser.VarTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.varType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarType([NotNull] ArislParser.VarTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.simpleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleType([NotNull] ArislParser.SimpleTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.simpleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleType([NotNull] ArislParser.SimpleTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.tupleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTupleType([NotNull] ArislParser.TupleTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.tupleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTupleType([NotNull] ArislParser.TupleTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.genericType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericType([NotNull] ArislParser.GenericTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.genericType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericType([NotNull] ArislParser.GenericTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.nestedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNestedType([NotNull] ArislParser.NestedTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.nestedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNestedType([NotNull] ArislParser.NestedTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.castType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCastType([NotNull] ArislParser.CastTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.castType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCastType([NotNull] ArislParser.CastTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArislParser.end"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnd([NotNull] ArislParser.EndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArislParser.end"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnd([NotNull] ArislParser.EndContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
