//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/ari/Desktop/C# Projects/ARISL/antlrfiles/Arisl.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ArislParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IArislVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] ArislParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDeclID([NotNull] ArislParser.FunctionDeclIDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>delegateDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDelegateDeclID([NotNull] ArislParser.DelegateDeclIDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>constructorDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructorDeclID([NotNull] ArislParser.ConstructorDeclIDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>classDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDeclID([NotNull] ArislParser.ClassDeclIDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>structDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDeclID([NotNull] ArislParser.StructDeclIDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>recordDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecordDeclID([NotNull] ArislParser.RecordDeclIDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>enumDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDeclID([NotNull] ArislParser.EnumDeclIDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>interfaceDeclID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceDeclID([NotNull] ArislParser.InterfaceDeclIDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ifStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatementID([NotNull] ArislParser.IfStatementIDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>whileStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatementID([NotNull] ArislParser.WhileStatementIDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatementID([NotNull] ArislParser.ForStatementIDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forEachStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachStatementID([NotNull] ArislParser.ForEachStatementIDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>returnStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatementID([NotNull] ArislParser.ReturnStatementIDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>objectCreationStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectCreationStatementID([NotNull] ArislParser.ObjectCreationStatementIDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>tryCatchStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTryCatchStatementID([NotNull] ArislParser.TryCatchStatementIDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>repeatUntilStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeatUntilStatementID([NotNull] ArislParser.RepeatUntilStatementIDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>switchStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStatementID([NotNull] ArislParser.SwitchStatementIDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionStatementID</c>
	/// labeled alternative in <see cref="ArislParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatementID([NotNull] ArislParser.ExpressionStatementIDContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.delegateDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDelegateDecl([NotNull] ArislParser.DelegateDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.recordDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecordDecl([NotNull] ArislParser.RecordDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDecl([NotNull] ArislParser.FunctionDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.repeatUntilStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeatUntilStatement([NotNull] ArislParser.RepeatUntilStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.classDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDecl([NotNull] ArislParser.ClassDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.constructorDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructorDecl([NotNull] ArislParser.ConstructorDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.structDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDecl([NotNull] ArislParser.StructDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.enumDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDecl([NotNull] ArislParser.EnumDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.interfaceDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceDecl([NotNull] ArislParser.InterfaceDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] ArislParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] ArislParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] ArislParser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.forEachStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachStatement([NotNull] ArislParser.ForEachStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] ArislParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.operatorOverloadStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorOverloadStatement([NotNull] ArislParser.OperatorOverloadStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.objectCreation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectCreation([NotNull] ArislParser.ObjectCreationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.interfaceBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceBlock([NotNull] ArislParser.InterfaceBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.interfaceMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceMember([NotNull] ArislParser.InterfaceMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.functionSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionSignature([NotNull] ArislParser.FunctionSignatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] ArislParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList([NotNull] ArislParser.ListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] ArislParser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PrimaryExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpression([NotNull] ArislParser.PrimaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BinaryExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryExpression([NotNull] ArislParser.BinaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParenthesisExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesisExpression([NotNull] ArislParser.ParenthesisExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PrefixExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefixExpression([NotNull] ArislParser.PrefixExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryExpression</c>
	/// labeled alternative in <see cref="ArislParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] ArislParser.UnaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>literalPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralPrimary([NotNull] ArislParser.LiteralPrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>tuplePrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuplePrimary([NotNull] ArislParser.TuplePrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>identifierPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierPrimary([NotNull] ArislParser.IdentifierPrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>methodCallPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCallPrimary([NotNull] ArislParser.MethodCallPrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>tableCallPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableCallPrimary([NotNull] ArislParser.TableCallPrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>blockPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockPrimary([NotNull] ArislParser.BlockPrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>listPrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListPrimary([NotNull] ArislParser.ListPrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>genericTypePrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericTypePrimary([NotNull] ArislParser.GenericTypePrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>typePrimary</c>
	/// labeled alternative in <see cref="ArislParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypePrimary([NotNull] ArislParser.TypePrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuple([NotNull] ArislParser.TupleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>varArgs</c>
	/// labeled alternative in <see cref="ArislParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarArgs([NotNull] ArislParser.VarArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>args</c>
	/// labeled alternative in <see cref="ArislParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgs([NotNull] ArislParser.ArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] ArislParser.ParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.prefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefix([NotNull] ArislParser.PrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.unaryOP"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryOP([NotNull] ArislParser.UnaryOPContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCall([NotNull] ArislParser.MethodCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.tableCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableCall([NotNull] ArislParser.TableCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] ArislParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.binaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryOp([NotNull] ArislParser.BinaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.tryCatchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTryCatchStatement([NotNull] ArislParser.TryCatchStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStatement([NotNull] ArislParser.SwitchStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.caseBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseBlock([NotNull] ArislParser.CaseBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.defaultBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefaultBlock([NotNull] ArislParser.DefaultBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModifier([NotNull] ArislParser.ModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVisibility([NotNull] ArislParser.VisibilityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] ArislParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.varType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarType([NotNull] ArislParser.VarTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.simpleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleType([NotNull] ArislParser.SimpleTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.tupleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTupleType([NotNull] ArislParser.TupleTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.genericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericType([NotNull] ArislParser.GenericTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.nestedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNestedType([NotNull] ArislParser.NestedTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.castType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCastType([NotNull] ArislParser.CastTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArislParser.end"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnd([NotNull] ArislParser.EndContext context);
}
